language: csharp
solution: ConsoleApp1.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
- dotnet restore
- dotnet test ./UnitTestProject1/UnitTest1.csproj
- dotnet build -c Release
- dotnet publish -c Release -o ./ConsoleApp1/publish
deploy:
on:
 tags: true
